; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = d1_mini_usb

[env]
platform = espressif8266
framework = arduino
build_type = release
monitor_speed = 115200
lib_deps = 
	adafruit/Adafruit NeoPixel@^1.15.5
	adafruit/Adafruit Unified Sensor@^1.1.15
	adafruit/DHT sensor library@^1.4.7
	bblanchon/ArduinoJson@^7.4.3
	crankyoldgit/IRremoteESP8266@^2.9.0
	tzapu/WiFiManager@^2.0.17
    paulstoffregen/Time@^1.6.1

[env:d1_mini_usb]
board = d1_mini
upload_protocol = esptool
upload_speed = 576000

[env:d1_mini_ota]
board = d1_mini
upload_protocol = espota
upload_port = 172.21.4.162
